defaults: &defaults
    machine: true
    steps:
      - attach_workspace:
          at: RPMS
      - run: docker run -u $UID:0 -h rpmbuild-el7.fmi.fi -v $PWD/RPMS:/home/rpmbuild/rpmbuild/RPMS fmidev/rpmbuild:el7 https://github.com/fmidev/$CIRCLE_JOB.git
      - persist_to_workspace:
          root: RPMS

version: 2
jobs:
  prepare:
    machine: true
    steps:
      - run: mkdir -p RPMS
      - run: sudo chgrp -R 0 RPMS
      - run: sudo chmod -R g=u RPMS
      - run: ls -la
      - persist_to_workspace:
          root: RPMS
          paths: .

  smartmet-library-newbase:
    <<: *defaults
  smartmet-library-imagine:
    <<: *defaults
  smartmet-library-macgyver:
    <<: *defaults
  smartmet-library-smarttools:
    <<: *defaults
  smartmet-library-calculator:
    <<: *defaults
  smartmet-library-gis:
    machine: true
    steps:
      - run:
          name: Build
          command: docker run -h rpmbuild-el7.fmi.fi --rm fmidev/rpmbuild:el7 https://github.com/fmidev/$CIRCLE_JOB.git
  smartmet-library-spine:
    machine: true
    steps:
      - run:
          name: Build
          command: docker run -h rpmbuild-el7.fmi.fi --rm fmidev/rpmbuild:el7 https://github.com/fmidev/$CIRCLE_JOB.git
  smartmet-qdtools:
    machine: true
    steps:
      - run:
          name: Build
          command: docker run -h rpmbuild-el7.fmi.fi --rm fmidev/rpmbuild:el7 https://github.com/fmidev/$CIRCLE_JOB.git
  deploy:
    machine: true
    steps:
      - run:
          name: Deploy
          command: echo Deploy


workflows:
  version: 2
  build-smartmet-qdtools:
    jobs:
      - prepare
      - smartmet-library-newbase:
          requires:
            - prepare
      - smartmet-library-imagine:
          requires:
            - prepare
      - smartmet-library-macgyver:
          requires:
            - smartmet-library-newbase
      - smartmet-library-smarttools:
          requires:
            - smartmet-library-newbase
      - smartmet-library-calculator:
          requires:
            - smartmet-library-macgyver
      - smartmet-library-gis:
          requires:
            - smartmet-library-macgyver
      - smartmet-library-spine:
          requires:
            - smartmet-library-gis
      - smartmet-qdtools:
          requires:
            - smartmet-library-newbase
            - smartmet-library-imagine
            - smartmet-library-macgyver
            - smartmet-library-smarttools
            - smartmet-library-calculator
            - smartmet-library-gis
            - smartmet-library-spine
      - deploy:
          requires:
            - smartmet-qdtools

